"use strict";(()=>{var e={};e.id=921,e.ids=[921],e.modules={399:e=>{e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},517:e=>{e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},8678:e=>{e.exports=import("pg")},972:(e,t,s)=>{s.a(e,async(e,r)=>{try{s.r(t),s.d(t,{originalPathname:()=>f,patchFetch:()=>p,requestAsyncStorage:()=>h,routeModule:()=>l,serverHooks:()=>d,staticGenerationAsyncStorage:()=>c});var a=s(9303),o=s(8716),n=s(670),i=s(9543),u=e([i]);i=(u.then?(await u)():u)[0];let l=new a.AppRouteRouteModule({definition:{kind:o.x.APP_ROUTE,page:"/api/staff/[id]/route",pathname:"/api/staff/[id]",filename:"route",bundlePath:"app/api/staff/[id]/route"},resolvedPagePath:"/Users/eaintmyatthu/AsspumptionUniversity/Database System/Project/Restaurant Management App/backend/src/app/api/staff/[id]/route.js",nextConfigOutput:"",userland:i}),{requestAsyncStorage:h,staticGenerationAsyncStorage:c,serverHooks:d}=l,f="/api/staff/[id]/route";function p(){return(0,n.patchFetch)({serverHooks:d,staticGenerationAsyncStorage:c})}r()}catch(e){r(e)}})},9303:(e,t,s)=>{e.exports=s(517)},9543:(e,t,s)=>{s.a(e,async(e,r)=>{try{s.r(t),s.d(t,{DELETE:()=>p,GET:()=>i,OPTIONS:()=>l,PUT:()=>u});var a=s(9248),o=s(6222),n=e([a]);a=(n.then?(await n)():n)[0];let h=async()=>{let e=await (0,a.I)(`SELECT column_name
     FROM information_schema.columns
     WHERE table_schema = 'public'
       AND table_name = 'app_user'
       AND column_name = ANY($1::text[])`,[["photo","salary"]]),t=new Set(e.rows.map(e=>e.column_name));return{hasPhoto:t.has("photo"),hasSalary:t.has("salary")}},c=async(e,{hasPhoto:t,hasSalary:s})=>(0,a.I)(`SELECT user_id AS id,
            name,
            email,
            role,
            dob AS date_of_birth,
            ${t?"photo":"NULL::text AS photo"},
            ${s?"salary":"0::numeric AS salary"}
     FROM app_user
     WHERE user_id = $1`,[e]);async function i(e,{params:t}){try{let e=Number(t.id),s=await h(),r=await c(e,s);if(0===r.rows.length)return(0,o.o)(Response.json({error:"Staff not found"},{status:404}));return(0,o.o)(Response.json(r.rows[0]))}catch(e){return(0,o.o)(Response.json({error:"Failed to fetch staff"},{status:500}))}}async function u(e,{params:t}){try{let s=await h(),r=["name","email","role","date_of_birth","dob","password"];s.hasSalary&&r.push("salary"),s.hasPhoto&&r.push("photo");let n=Number(t.id),i=await e.json(),u=[],p=[];for(let e of r)if(Object.prototype.hasOwnProperty.call(i,e)){let t=i[e];if(void 0===t)continue;if("password"===e){let e=String(t||"").trim();if(!e)continue;u.push("password = $"+(p.length+1)),p.push(e)}else if("date_of_birth"===e||"dob"===e)u.push("dob = $"+(p.length+1)),p.push(t||null);else if("salary"===e){let e=Number(t);if(!Number.isFinite(e))return(0,o.o)(Response.json({error:"Invalid salary"},{status:400}));u.push("salary = $"+(p.length+1)),p.push(Math.round(e))}else u.push(e+" = $"+(p.length+1)),p.push(t)}if(0===u.length){if(Object.keys(i||{}).length>0){let e=await c(n,s);if(0===e.rows.length)return(0,o.o)(Response.json({error:"Staff not found"},{status:404}));return(0,o.o)(Response.json(e.rows[0]))}return(0,o.o)(Response.json({error:"No fields to update"},{status:400}))}p.push(n);let l=s.hasPhoto?"photo":"NULL::text AS photo",d=s.hasSalary?"salary":"0::numeric AS salary",f=await (0,a.I)(`UPDATE app_user SET ${u.join(", ")} WHERE user_id = $${p.length}
       RETURNING user_id AS id, name, email, role, dob AS date_of_birth, ${l}, ${d}`,p);if(0===f.rows.length)return(0,o.o)(Response.json({error:"Staff not found"},{status:404}));return(0,o.o)(Response.json(f.rows[0]))}catch(e){return(0,o.o)(Response.json({error:"Failed to update staff"},{status:500}))}}async function p(e,{params:t}){try{let e=Number(t.id),s=await (0,a.I)("DELETE FROM app_user WHERE user_id = $1 RETURNING user_id",[e]);if(0===s.rows.length)return(0,o.o)(Response.json({error:"Staff not found"},{status:404}));return(0,o.o)(Response.json({success:!0}))}catch(e){return(0,o.o)(Response.json({error:"Failed to delete staff"},{status:500}))}}async function l(){return(0,o.c)()}r()}catch(e){r(e)}})},6222:(e,t,s)=>{s.d(t,{c:()=>o,o:()=>a});let r={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"GET,POST,PUT,DELETE,OPTIONS","Access-Control-Allow-Headers":"Content-Type, Authorization"},a=e=>(Object.entries(r).forEach(([t,s])=>{e.headers.set(t,s)}),e),o=()=>new Response(null,{status:204,headers:r})},9248:(e,t,s)=>{s.a(e,async(e,r)=>{try{s.d(t,{I:()=>i});var a=s(8678),o=e([a]);let n=new(a=(o.then?(await o)():o)[0]).Pool({connectionString:process.env.DATABASE_URL}),i=(e,t)=>n.query(e,t);r()}catch(e){r(e)}})}};var t=require("../../../../webpack-runtime.js");t.C(e);var s=e=>t(t.s=e),r=t.X(0,[948],()=>s(972));module.exports=r})();