"use strict";(()=>{var e={};e.id=991,e.ids=[991],e.modules={399:e=>{e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},517:e=>{e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},8678:e=>{e.exports=import("pg")},613:(e,t,n)=>{n.a(e,async(e,i)=>{try{n.r(t),n.d(t,{originalPathname:()=>_,patchFetch:()=>u,requestAsyncStorage:()=>p,routeModule:()=>c,serverHooks:()=>l,staticGenerationAsyncStorage:()=>d});var a=n(9303),r=n(8716),o=n(670),s=n(9979),m=e([s]);s=(m.then?(await m)():m)[0];let c=new a.AppRouteRouteModule({definition:{kind:r.x.APP_ROUTE,page:"/api/menu/route",pathname:"/api/menu",filename:"route",bundlePath:"app/api/menu/route"},resolvedPagePath:"/Users/eaintmyatthu/AsspumptionUniversity/Database System/Project/Restaurant Management App/backend/src/app/api/menu/route.js",nextConfigOutput:"",userland:s}),{requestAsyncStorage:p,staticGenerationAsyncStorage:d,serverHooks:l}=c,_="/api/menu/route";function u(){return(0,o.patchFetch)({serverHooks:l,staticGenerationAsyncStorage:d})}i()}catch(e){i(e)}})},9303:(e,t,n)=>{e.exports=n(517)},9979:(e,t,n)=>{n.a(e,async(e,i)=>{try{n.r(t),n.d(t,{GET:()=>s,OPTIONS:()=>u,POST:()=>m});var a=n(9248),r=n(6222),o=e([a]);async function s(){try{let e=await (0,a.I)(`SELECT mi.menu_item_id AS id,
              mi.menu_item_id AS "menuItemId",
              mi.name,
              COALESCE(MIN(mic.category), 'Main') AS category,
              mi.price,
              mi.photo AS image,
              mi.is_available
       FROM menu_item mi
       LEFT JOIN menu_item_category mic ON mic.menu_item_id = mi.menu_item_id
       GROUP BY mi.menu_item_id
       ORDER BY mi.menu_item_id ASC`);return(0,r.o)(Response.json(e.rows))}catch(e){return(0,r.o)(Response.json({error:"Failed to fetch menu"},{status:500}))}}async function m(e){try{let{name:t,category:n="Main",price:i=0,image:o=null,is_available:s=!0}=await e.json()||{};if(!t)return(0,r.o)(Response.json({error:"Name is required"},{status:400}));let m=(await (0,a.I)(`INSERT INTO menu_item (name, price, is_available, photo)
       VALUES ($1, $2, $3, $4)
       RETURNING menu_item_id AS id, menu_item_id AS "menuItemId", name, price, photo AS image, is_available`,[t,i,s,o])).rows[0];return n&&await (0,a.I)("INSERT INTO menu_item_category (menu_item_id, category) VALUES ($1, $2)",[m.id,n]),(0,r.o)(Response.json({...m,category:n},{status:201}))}catch(e){return(0,r.o)(Response.json({error:"Failed to create menu item"},{status:500}))}}async function u(){return(0,r.c)()}a=(o.then?(await o)():o)[0],i()}catch(e){i(e)}})},6222:(e,t,n)=>{n.d(t,{c:()=>r,o:()=>a});let i={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"GET,POST,PUT,DELETE,OPTIONS","Access-Control-Allow-Headers":"Content-Type, Authorization"},a=e=>(Object.entries(i).forEach(([t,n])=>{e.headers.set(t,n)}),e),r=()=>new Response(null,{status:204,headers:i})},9248:(e,t,n)=>{n.a(e,async(e,i)=>{try{n.d(t,{I:()=>s});var a=n(8678),r=e([a]);let o=new(a=(r.then?(await r)():r)[0]).Pool({connectionString:process.env.DATABASE_URL}),s=(e,t)=>o.query(e,t);i()}catch(e){i(e)}})}};var t=require("../../../webpack-runtime.js");t.C(e);var n=e=>t(t.s=e),i=t.X(0,[948],()=>n(613));module.exports=i})();