"use strict";(()=>{var e={};e.id=108,e.ids=[108],e.modules={399:e=>{e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},517:e=>{e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},8678:e=>{e.exports=import("pg")},1176:(e,t,i)=>{i.a(e,async(e,n)=>{try{i.r(t),i.d(t,{originalPathname:()=>_,patchFetch:()=>u,requestAsyncStorage:()=>p,routeModule:()=>c,serverHooks:()=>l,staticGenerationAsyncStorage:()=>d});var o=i(9303),r=i(8716),a=i(670),s=i(146),m=e([s]);s=(m.then?(await m)():m)[0];let c=new o.AppRouteRouteModule({definition:{kind:r.x.APP_ROUTE,page:"/api/menu/[id]/route",pathname:"/api/menu/[id]",filename:"route",bundlePath:"app/api/menu/[id]/route"},resolvedPagePath:"/Users/eaintmyatthu/AsspumptionUniversity/Database System/Project/Restaurant Management App/backend/src/app/api/menu/[id]/route.js",nextConfigOutput:"",userland:s}),{requestAsyncStorage:p,staticGenerationAsyncStorage:d,serverHooks:l}=c,_="/api/menu/[id]/route";function u(){return(0,a.patchFetch)({serverHooks:l,staticGenerationAsyncStorage:d})}n()}catch(e){n(e)}})},9303:(e,t,i)=>{e.exports=i(517)},146:(e,t,i)=>{i.a(e,async(e,n)=>{try{i.r(t),i.d(t,{DELETE:()=>u,GET:()=>s,OPTIONS:()=>c,PUT:()=>m});var o=i(9248),r=i(6222),a=e([o]);o=(a.then?(await a)():a)[0];let p=["name","category","price","image","is_available"];async function s(e,{params:t}){try{let e=Number(t.id),i=await (0,o.I)(`SELECT mi.menu_item_id AS id,
              mi.menu_item_id AS "menuItemId",
              mi.name,
              COALESCE(MIN(mic.category), 'Main') AS category,
              mi.price,
              mi.photo AS image,
              mi.is_available
       FROM menu_item mi
       LEFT JOIN menu_item_category mic ON mic.menu_item_id = mi.menu_item_id
       WHERE mi.menu_item_id = $1
       GROUP BY mi.menu_item_id`,[e]);if(0===i.rows.length)return(0,r.o)(Response.json({error:"Menu item not found"},{status:404}));return(0,r.o)(Response.json(i.rows[0]))}catch(e){return(0,r.o)(Response.json({error:"Failed to fetch menu item"},{status:500}))}}async function m(e,{params:t}){try{let i=Number(t.id),n=await e.json(),a=[],s=[];for(let e of p)Object.prototype.hasOwnProperty.call(n,e)&&("image"===e?(a.push("photo = $"+(s.length+1)),s.push(n[e])):"category"===e||(a.push(e+" = $"+(s.length+1)),s.push(n[e])));if(0===a.length){if(Object.prototype.hasOwnProperty.call(n||{},"category")){let e=await (0,o.I)(`SELECT mi.menu_item_id AS id,
                  mi.menu_item_id AS "menuItemId",
                  mi.name,
                  COALESCE(MIN(mic.category), 'Main') AS category,
                  mi.price,
                  mi.photo AS image,
                  mi.is_available
           FROM menu_item mi
           LEFT JOIN menu_item_category mic ON mic.menu_item_id = mi.menu_item_id
           WHERE mi.menu_item_id = $1
           GROUP BY mi.menu_item_id`,[i]);if(0===e.rows.length)return(0,r.o)(Response.json({error:"Menu item not found"},{status:404}));return(0,r.o)(Response.json(e.rows[0]))}return(0,r.o)(Response.json({error:"No fields to update"},{status:400}))}s.push(i);let m=await (0,o.I)(`UPDATE menu_item SET ${a.join(", ")} WHERE menu_item_id = $${s.length}
       RETURNING menu_item_id AS id, menu_item_id AS "menuItemId", name, price, photo AS image, is_available`,s);if(0===m.rows.length)return(0,r.o)(Response.json({error:"Menu item not found"},{status:404}));let u=m.rows[0];Object.prototype.hasOwnProperty.call(n||{},"category")&&(await (0,o.I)("DELETE FROM menu_item_category WHERE menu_item_id = $1",[i]),n.category&&await (0,o.I)("INSERT INTO menu_item_category (menu_item_id, category) VALUES ($1, $2)",[i,n.category]));let c=Object.prototype.hasOwnProperty.call(n||{},"category")&&n.category?n.category:void 0;return(0,r.o)(Response.json({...u,...c?{category:c}:{}}))}catch(e){return(0,r.o)(Response.json({error:"Failed to update menu item"},{status:500}))}}async function u(e,{params:t}){try{let e=Number(t.id),i=await (0,o.I)("DELETE FROM menu_item WHERE menu_item_id = $1 RETURNING menu_item_id",[e]);if(0===i.rows.length)return(0,r.o)(Response.json({error:"Menu item not found"},{status:404}));return(0,r.o)(Response.json({success:!0}))}catch(e){return(0,r.o)(Response.json({error:"Failed to delete menu item"},{status:500}))}}async function c(){return(0,r.c)()}n()}catch(e){n(e)}})},6222:(e,t,i)=>{i.d(t,{c:()=>r,o:()=>o});let n={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"GET,POST,PUT,DELETE,OPTIONS","Access-Control-Allow-Headers":"Content-Type, Authorization"},o=e=>(Object.entries(n).forEach(([t,i])=>{e.headers.set(t,i)}),e),r=()=>new Response(null,{status:204,headers:n})},9248:(e,t,i)=>{i.a(e,async(e,n)=>{try{i.d(t,{I:()=>s});var o=i(8678),r=e([o]);let a=new(o=(r.then?(await r)():r)[0]).Pool({connectionString:process.env.DATABASE_URL}),s=(e,t)=>a.query(e,t);n()}catch(e){n(e)}})}};var t=require("../../../../webpack-runtime.js");t.C(e);var i=e=>t(t.s=e),n=t.X(0,[948],()=>i(1176));module.exports=n})();