server {
  listen 80;
  server_name webdevfromthitlwin.koreacentral.cloudapp.azure.com;

  location / {
    proxy_pass http://frontend-server:80;
  }

  location /api/ {
    proxy_pass http://backend-server:3003;
  }
}