"use strict";(()=>{var e={};e.id=281,e.ids=[281],e.modules={399:e=>{e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},517:e=>{e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},8678:e=>{e.exports=import("pg")},1908:(e,t,a)=>{a.a(e,async(e,r)=>{try{a.r(t),a.d(t,{originalPathname:()=>m,patchFetch:()=>u,requestAsyncStorage:()=>c,routeModule:()=>l,serverHooks:()=>h,staticGenerationAsyncStorage:()=>d});var s=a(9303),o=a(8716),n=a(670),i=a(7281),p=e([i]);i=(p.then?(await p)():p)[0];let l=new s.AppRouteRouteModule({definition:{kind:o.x.APP_ROUTE,page:"/api/staff/route",pathname:"/api/staff",filename:"route",bundlePath:"app/api/staff/route"},resolvedPagePath:"/Users/eaintmyatthu/AsspumptionUniversity/Database System/Project/Restaurant Management App/backend/src/app/api/staff/route.js",nextConfigOutput:"",userland:i}),{requestAsyncStorage:c,staticGenerationAsyncStorage:d,serverHooks:h}=l,m="/api/staff/route";function u(){return(0,n.patchFetch)({serverHooks:h,staticGenerationAsyncStorage:d})}r()}catch(e){r(e)}})},9303:(e,t,a)=>{e.exports=a(517)},7281:(e,t,a)=>{a.a(e,async(e,r)=>{try{a.r(t),a.d(t,{GET:()=>i,OPTIONS:()=>u,POST:()=>p});var s=a(9248),o=a(6222),n=e([s]);s=(n.then?(await n)():n)[0];let l=async()=>{let e=await (0,s.I)(`SELECT column_name
     FROM information_schema.columns
     WHERE table_schema = 'public'
       AND table_name = 'app_user'
       AND column_name = ANY($1::text[])`,[["photo","salary"]]),t=new Set(e.rows.map(e=>e.column_name));return{hasPhoto:t.has("photo"),hasSalary:t.has("salary")}};async function i(){try{let{hasPhoto:e,hasSalary:t}=await l(),a=await (0,s.I)(`SELECT user_id AS id,
              name,
              email,
              role,
              dob AS date_of_birth,
              ${e?"photo":"NULL::text AS photo"},
              ${t?"salary":"0::numeric AS salary"}
       FROM app_user
       ORDER BY user_id ASC`);return(0,o.o)(Response.json(a.rows))}catch(e){return console.error("GET /api/staff failed",e),(0,o.o)(Response.json({error:"Failed to fetch staff"},{status:500}))}}async function p(e){try{let{hasPhoto:t,hasSalary:a}=await l(),{name:r,email:n,role:i="staff",date_of_birth:p,dob:u,password:c=null,salary:d=0}=await e.json()||{};if(!r||!n||!c)return(0,o.o)(Response.json({error:"Name, email, and password are required"},{status:400}));let h=["name","email","role","dob","password"],m=[r,n,i,u??p??null,c];a&&(h.push("salary"),m.push(d));let f=h.map((e,t)=>`$${t+1}`).join(", "),A=(await (0,s.I)(`INSERT INTO app_user (${h.join(", ")})
       VALUES (${f})
       RETURNING user_id AS id, name, email, role, dob AS date_of_birth, ${t?"photo":"NULL::text AS photo"}, ${a?"salary":"0::numeric AS salary"}`,m)).rows[0];return(0,o.o)(Response.json(A,{status:201}))}catch(e){return console.error("POST /api/staff failed",e),(0,o.o)(Response.json({error:"Failed to create staff"},{status:500}))}}async function u(){return(0,o.c)()}r()}catch(e){r(e)}})},6222:(e,t,a)=>{a.d(t,{c:()=>o,o:()=>s});let r={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"GET,POST,PUT,DELETE,OPTIONS","Access-Control-Allow-Headers":"Content-Type, Authorization"},s=e=>(Object.entries(r).forEach(([t,a])=>{e.headers.set(t,a)}),e),o=()=>new Response(null,{status:204,headers:r})},9248:(e,t,a)=>{a.a(e,async(e,r)=>{try{a.d(t,{I:()=>i});var s=a(8678),o=e([s]);let n=new(s=(o.then?(await o)():o)[0]).Pool({connectionString:process.env.DATABASE_URL}),i=(e,t)=>n.query(e,t);r()}catch(e){r(e)}})}};var t=require("../../../webpack-runtime.js");t.C(e);var a=e=>t(t.s=e),r=t.X(0,[948],()=>a(1908));module.exports=r})();